Fix JS Cup
Terasology/CoreBlocks pull request #4
Opened 2020-04-03 15:50 UTC by ktksan

Change water to targetable.

2020-04-03 16:03 UTC, ktksan commented
This has been done to support the PR: https://github.com/Terasology/EdibleSubstance/pull/1

2020-04-05 18:52 UTC, skaldarnar requested changes
Just tested this out together with https://github.com/Terasology/EdibleSubstance/pull/1, and while drinking water with the cup works fine, water blocks cannot be replaced anymore. Neither when standing on shore and looking into water, nor when underwater. Also, it's not possible to mine blocks when underwater (the targeted block is always the water block).

We'll need to find another way to make this happen... I'm wondering whether we can reverse engineer what @Josharias did implement there...

2020-04-05 18:52 UTC, skaldarnar commented on assets/blocks/liquid/Water.block
> +    "targetable": true,
Unfortunately, this leads to water blocks not being replaceable anymore 😢

2020-04-09 22:24 UTC, jdrueckert commented
Fixed the root cause (filling containers) in
https://github.com/Terasology/Fluid/pull/15 and
https://github.com/Terasology/ManualLabor/pull/27
which resulted in drinking from WoodenCup being possible again as a side effect.

Anyway, thank you for trying to fix it this way :) I'll close this PR as this is no longer an issue.

2020-04-09 22:24 UTC, closed without merging